[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs/ |
    \.git/ |
    \.hg/ |
    \.mypy_cache/ |
    \.nox/ |
    \.pytest_cache/ |
    \.tox/ |
    \.venv/ |
    /venv   |
    _build/ |
    buck-out/ |
    build/ |
    dist/
)/
'''

[tool.black.config]
# These are optional configurations that you can tweak to your liking
skip-string-normalization = true
